catalog:
  '@antfu/eslint-config': ^5.4.1
  '@tailwindcss/vite': ^4.1.16
  '@tarocch1/eslint-config': ^4.0.1
  '@types/lodash-es': ^4.17.12
  '@types/node': ^24.9.1
  '@vitejs/plugin-vue': ^6.0.1
  '@vue/tsconfig': ^0.8.1
  animate.css: ^4.1.1
  eslint: ^9.38.0
  husky: ^9.1.7
  lint-staged: ^16.2.4
  lodash-es: ^4.17.21
  prettier: ^3.6.2
  shiki: ^3.14.0
  tailwindcss: ^4.1.16
  typescript: ^5.9.2
  vite: ^7.1.12
  vue: ^3.5.22
  vue-router: ^4.6.3

catalogMode: strict
