name: Main Workflow

on:
  push:
    branches:
      - 'main'

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: checkout_gh-pages
        name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'gh-pages'
          path: 'tmp'
      - id: setup_nodejs
        name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - id: npm_ci
        name: npm ci
        run: npm ci
      - id: npm_run_build
        name: Build
        run: npm run build
      - id: deploy
        name: Deploy
        run: bash ./.github/actions/main/deploy.sh
